### ISSUE TITLE
Mosaic segfaults if a "video grabber" object is added while no webcam is present in the system

### ISSUE THREAD

**Issue by somas95** [d3cod3/Mosaic#12]
SO: Linux (tested in Fedora 30 and Debian 10.1)
Just what the title says. If no video device is attached to the system, Mosaic segfaults when adding a video grabber object or when opening a patch with a video grabber object. 

If a debug flag is available I could try to get some traces

**Comment by d3cod3** [comment]
Thanks for the info, fixing it right now!

There is a control for the number of detected devices in the object setup ( https://github.com/d3cod3/ofxVisualProgramming/blob/master/src/objects/video/VideoGrabber.cpp ) but probably not fine tuned...

checking it!

**Comment by d3cod3** [comment]
Fixed and pushed!

https://github.com/d3cod3/ofxVisualProgramming/commit/5f3c12aac66fc23517daa33e8e6262404e9bf36f

**Comment by somas95** [comment]
It still segfaults when opening the "config" menu of the video grabber object if no video device is present

**Comment by d3cod3** [comment]
Strange! Not happening to me, it open the config menu and "No Device Present" label appear.

But anyway, i'll check it again and fix it better!

Thanks

**Comment by d3cod3** [comment]
Strong fixed now!

https://github.com/d3cod3/ofxVisualProgramming/commit/d8759feadc819b6e4a5da7940616ac4ee46b50c6

Try it and tell me if it's working now
