### ISSUE TITLE
No text editor is opened if atom is not installed

### ISSUE THREAD

**Issue by somas95** [d3cod3/Mosaic#13]
Theoretically the system's default text editor should be launched when trying to edit scripts, shaders, etc if Atom is not installed, but at least on Linux it doesn't happen

**Comment by somas95** [comment]
I see it's hardcoded and no alternative is set:
https://github.com/d3cod3/ofxVisualProgramming/blob/9a44632bd044ea4dd8ce1ad19122b1150680eef6/src/objects/scripting/ShaderObject.cpp#L687
At least on Linux xdg-open can be used to let the system manage that. It's standard and desktop-agnostic

**Comment by d3cod3** [comment]
Yes, this is something i was dragging from long time ago, it need to be fixed!

I'll get to it this week, thanks for the tip about xdg-open!

**Comment by d3cod3** [comment]
Solved! Now Mosaic has an integrated code editor builded with imgui library
