### ISSUE TITLE
Plugin System

### ISSUE THREAD

**Issue by d3cod3** [d3cod3/Mosaic#16]
Mosaic plugin mechanism integration. based on [PUGG](http://pugg.sourceforge.net/)

https://github.com/d3cod3/Mosaic-Plugin

**Comment by d3cod3** [comment]
I just added a new branch in the plugin repo, to test it with the new params and imgui refactoring

https://github.com/d3cod3/Mosaic-Plugin/tree/refactor-params-and-gui

**Comment by d3cod3** [comment]
Compile and works out of the box!

**Comment by Daandelange** [comment]
What's the state of this ? Plugins compile, but do they load into Mosaic ?

**Comment by d3cod3** [comment]
Untouched right now, i still have to check it with all the last changes on ofxVP side, i'll let you know as i try it!

**Comment by d3cod3** [comment]
The plugin system with the new GUI mechanism is perfectly working!!!

Just needed to store the main imgui context in a variable ( in ImGuiEx::NodeCanvas ), and set it in the plugin objects from there.

![mosaicScreenshot_200831](https://user-images.githubusercontent.com/141075/91749408-b66c7c80-ebc1-11ea-8e4a-6387a94be640.jpg)

All kind of objects are working, in the screenshot you can see the 4 objects from the plugin template.

I'm 36 objects to go for the 0.4.0...

**Comment by Daandelange** [comment]
Just for the record, maybe overkill, but there's also [GLib](https://github.com/GNOME/glib/tree/main) for dynamic loading. (Not sure if that would correct the embedded-OF-within-all-plugins issue)
