### ISSUE TITLE
The Ubuntu release file fails to be uncompressed

### ISSUE THREAD

**Issue by enrike** [d3cod3/Mosaic#2]
the file 

https://github.com/d3cod3/Mosaic/releases/download/0.1.6/Mosaic_v0.1.6_linux64_ubuntu18.04_release.tar.gz

fails to be uncompressed. it outputs

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by d3cod3** [comment]
Try tar -xvzf Mosaic_v0.1.6_linux64_ubuntu18.04_release.tar.gz from terminal, for me it's working on linux and on osx. Maybe the file was not completely downloaded?

```bash
tar -xvzf Mosaic_v0.1.6_linux64_ubuntu18.04_release.tar.gz
```

**Comment by enrike** [comment]
funny. It says the file does not exist. But it is there and the name is correct. I tried with two different machines running latest version of Ubuntu. I downloaded the file several times in both machines. 


// the file does exist
$ test -f UnitySetup-2018.2.6f1 ; echo $?
0

// but tar cannot find it?
$ tar -xvfz Mosaic_v0.1.6_linux64_ubuntu18.04_release.tar.gz
tar: z: Ezin da open: No such file or directory
tar: Error is not recoverable: exiting now

The I opened from xarchiver and I can uncompress it fine that way. But when I run ./Mosaic I get 

$ ./Mosaic
Illegal instruction (core dumped)

not sure if this is to do with the uncompression not being right. however there is no error while uncompressing

**Comment by d3cod3** [comment]
Ok, not sure right now about the tar error, but the problem now is the running of Mosaic, do you have some more stderror output apart from "Illegal instruction..." ?

Anyway, right now the 100% secure way to have Mosaic up&running on every linux machine is to compile it. The actual linux releases are betas that i'm testing on some available linux boxes, they are not fully tested on a huge variety of machines so, again, the best way to have Mosaic running fine is to follow the instruction for [compiling](https://github.com/d3cod3/Mosaic#compiling)

Please let me know if any issues while compiling, the short list for it is:

1 - download and install OF 0.10 from official webpage (0.10.1 works too)
2 - follow openframeworks install instructions (install dependencies script)
3 - install qtcreator 4.6.1
3 - install all required ofxAddons (git clone)
4 - clone Mosaic from github
5 - open Mosaic project from qtcreator and compile

**Comment by enrike** [comment]
ok!

**Comment by enrike** [comment]
compiled fine here! maybe it would be good to add somewhere that Mosaic has to be placed under OF/apps/MyApps for compilation. I havent used OF for a few years and had forgoten about it.

but it seems to work fine. thanks!

**Comment by d3cod3** [comment]
Great! I will add the info, is a common detail in OF projects, but i'll specifiy better in the readme.
Thanks for the tip! If you're interested in contribute to the project and crfeate new objects, just let me know and we'll get to it!
