### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by ferhoyo** [d3cod3/Mosaic#3]
I could not update Mosaic I had installed on Ubuntu 18.04 with update_mosaic.sh
I've got this error:
`/opt/openFrameworks/addons/ofxWarp/src/ofxWarp/WarpBase.cpp:465:10: warning: ‘index’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   return index;
          ^~~~~
make[1]: se sale del directorio '/opt/openFrameworks/apps/d3cod3/Mosaic'
/opt/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:124: recipe for target 'Release' failed
make: *** [Release] Error 2
"make -j$NUMPU Release" command failed with exit code 2.`

I wanted to try the new projection mapping object.

**Comment by d3cod3** [comment]
Hello there, sorry but the update_mosaic.sh was deprecated and i forget to delete it.
Right now, the same script you've used to install mosaic, can be used for update and re-compile, it will automatically detect that Mosaic is already installed and will just check/update/re-compile.

I've just deleted the deprecated gist, so no one will fall for the same!

Let me know if everything is working fine after the update.

**Comment by ferhoyo** [comment]
Hi
thanks for the reply.
I run install_mosaic_ubuntu.sh and I got exactly the same error
`/opt/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:124: recipe for target 'Release' failed
make: *** [Release] Error 2
"make -j$NUMPU Release" command failed with exit code 2.`

Should I manually delete the previous installation?

**Comment by d3cod3** [comment]
No, don't delete the previous install.

First, did you run it with:   ./install_mosaic_ubuntu.sh ?

Then, it seem like something related with the system threads available, try this in a command line:

```bash
nproc
```

It should return a number, this are the your system max threads (double the cores of your processor)

Is really awkward that the script worked for the install and is not working now!

If is still not working, you can try to hack the script, go to line 51, you will find this:

```bash
NPROC="$( nproc )"
NUMPU="1"
if [ $NPROC -gt "1" ]; then
    NUMPU="$( expr $NPROC / 2 )"
else
    NUMPU="1"
fi
```

change it like this:

```bash
#NPROC="$( nproc )"
#NUMPU="1"
#if [ $NPROC -gt "1" ]; then
#    NUMPU="$( expr $NPROC / 2 )"
#else
#   NUMPU="1"
#fi

NUMPU="1"
```

this will force to use only one thread for compiling.

Try this and let me know, in the meantime i will check on some other linux box.

**Comment by ferhoyo** [comment]
Hello again

Yes I did run the script with sudo ./install_mosaic_ubuntu.sh
The number of processes is 32 (nproc)
Procesador: Intel® Xeon(R) CPU E5-2620 v4 @ 2.10GHz × 32 

I hacked the script as per your instructions and with 1 process I've got the same error:

`/opt/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:124: recipe for target 'Release' failed
make: *** [Release] Error 2
"make -j$NUMPU Release" command failed with exit code 2.`

**Comment by d3cod3** [comment]
Ok, let's try this then:

got to line 309, you'll find:

```bash
make -j$NUMPU Release
```

change that to:

```bash
make Release
```

or to use 8 threads for example:

```bash
make -j8 Release
```

This should silence your error.

In the meantime i'll investigate the issue...

**Comment by ferhoyo** [comment]
Hello

Changing the line 309 to `make Release`

I had this error

`from /opt/openFrameworks/apps/d3cod3/Mosaic/src/ofApp.cpp:33:
/opt/openFrameworks/addons/ofxVisualProgramming/src/objects/windowing/ProjectionMapping.h:37:10: fatal error: ofxMtlMapping2D.h: No existe el archivo o el directorio
 #include "ofxMtlMapping2D.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
/opt/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:215: recipe for target 'obj/linux64/Release/src/ofApp.o' failed
make[1]: *** [obj/linux64/Release/src/ofApp.o] Error 1
make[1]: se sale del directorio '/opt/openFrameworks/apps/d3cod3/Mosaic'
/opt/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:124: recipe for target 'Release' failed
make: *** [Release] Error 2
"make Release" command failed with exit code 2.`

Changing the line 309 to `make -j8 Release`

I have a different error:

`Compiling Mosaic for Release
make[1]: se entra en el directorio '/opt/openFrameworks/apps/d3cod3/Mosaic'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal libcurl glfw3 rtaudio libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
with PKG_CONFIG_LIBDIR=
make[1]: *** No hay ninguna regla para construir el objetivo '/opt/openFrameworks/addons/obj/linux64/Release/ofxMtlMapping2D/./src/ofApp.o', necesario para 'bin/Mosaic'.  Alto.
make[1]: *** Se espera a que terminen otras tareas....
make[1]: se sale del directorio '/opt/openFrameworks/apps/d3cod3/Mosaic'
/opt/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:124: recipe for target 'Release' failed
make: *** [Release] Error 2
"make -j8 Release" command failed with exit code 2.`

**Comment by ferhoyo** [comment]
I've renamed /opt/openFrameworks to try a new installation and now it can't find `librtaudio4`

`No se ha podido localizar el paquete librtaudio4
"apt install git curl wget libpython2.7-dev libcurl3 librtaudio4 libjack0 libjack-jackd2-dev" command failed with exit code 100.`

I'm on Ubuntu 18.04

**Comment by d3cod3** [comment]
Yes, it's the last addition for linux mint installation, i didn't check it, sorry!

Just change that line from 

apt install git curl wget libpython2.7-dev libcurl3 librtaudio4 libjack0 libjack-jackd2-dev

to

apt install git curl wget libpython2.7-dev

Anyway, i've just fixed the ubuntu script and added a new specific one for linux mint.

And about the real error, it's the last addon addition i've made for the projection mapping object, i forgot to add it to the install/update script, i've just fixed all the scripts, do not rename and reinstall openframeworks, just download the ubuntu script again and test it.

Thank you for helping me with this!

**Comment by ferhoyo** [comment]
I did download the latest script and it worked great on my Ubuntu 18.04
Thanks a lot
