### ISSUE TITLE
Inspector

### ISSUE THREAD

**Issue by Daandelange** [d3cod3/Mosaic#30]
It would be nice to have an inspector that shows information about the selected node(s), or the patch -file info when you select the background.

Creating the issue to start thinking about this.

**Comment by d3cod3** [comment]
The inspector is ready!!!

![Sin título](https://user-images.githubusercontent.com/141075/93001799-e60c7480-f531-11ea-960b-af56282d7e0d.jpeg)

Working perfectly, really happy with the result!


I'm 5 objects away from completing the port to imgui, probably monday i'm going to pull the refactor branch to master, i'll let you know.

**Comment by Daandelange** [comment]
Wow, amazing work ! 👍   (I'm happy we didn't wait for ofxVPParams refactoring).
I just pulled & played around a little, the UI feels way better this way.
2 quick thoughts: 
 - The selected node could be more obvious / visible ?
 - Add more (left?) padding to the inspector ?

**Comment by d3cod3** [comment]
Yes, i've already fixed some details around the inspector design, i'll add some more padding too!

And about the selected node, i'm trying different things, i do not want to add color, and right now it is just changing the header color to some lighter gray, so yes, too subtle indeed.

I'll sleep on it and tomorrow i'll find something more obvious.

By the way, the imgui porting is finished, i've cleaned a lot of stuff, reduced dependencies and the plugin system is working really fine, everything, including textures without the needs of using ofPixels ( so, pretty fast ); i'm updating the readme files and cleaning a little bit more, probably tomorrow i'll pull to master ( the new Mosaic release must be available next week for the start of classes at the university ).

Anyway, there's still a lot to do, but i'm really happy at the present results.

I'll let you know when i'll pull to master.
