### ISSUE TITLE
Addon dependency tool

### ISSUE THREAD

**Issue by Daandelange** [d3cod3/Mosaic#35]
#34 integrates a beta version for a dependency checker.
Only tested on osx 10.12 so far. Feedback is appreciated.

I'd like to extend it at least with the following functionality.
- [x] Test multi-platform
- [ ] Parse addon dependencies (parsing `addons/ofxXyzAddon/addons.make`)
- [x] Add option to install (clone)
- [x] Add option to update repos and their submodules (clone)
- [x] Add option to sync `addons.txt` with `addons.make` for easier dependency maintenance.

What about creating a `Mosaic/utilities/addonTool/check_addons.sh` folder to host this script ?
I could also create a new repo for it (useful for other OF projects) and make it a Mosaic submodule.

Any other ideas ?

**Comment by d3cod3** [comment]
Yes, i was checking the script yesterday, works on linux ( ubuntu/debian, will test on others ) perfectly!

I like the submodule approach, i'm going to add a specific folder for scripts ( Mosaic/scripts/ ) then we can store there all scripts utils as submodules ( this one as others in the future )

With the addons.txt ( maybe could be better to use addonsDependencies.txt ? ) syncing, it is an universal tool for every OF application, i think it's a great contribution!

I'll wait for your repo with this addonTool ( suggestion names: ofxAddonChecker, ofxAddonTool, ofxAddonManager ) and when is ready i'll add the folder and the submodule inside.

**Comment by Daandelange** [comment]
Ok, the initial repo is setup here.
https://github.com/Daandelange/ofxAddonTool
(Lots of changes under the hood, but features are not yet extended.)
It should run out of the box; do you want to install the submodule ? (otherwise I can make a PR)

**Comment by d3cod3** [comment]
Already added as submodule!
Tested and running fine, just one small issue, in the readme in Installation:

you have ```brew install figment```

but it must be ```brew install figlet```

figment is throwing an error: No formulae found in taps

**Comment by d3cod3** [comment]
Just tested on MSYS2 ( windows ), it works but do not visualize right

![Sin título](https://user-images.githubusercontent.com/141075/95172377-85cac480-07b7-11eb-91fa-958eb3edc6b3.jpeg)

Probably because it needs figlet or toilet, but ```pacman -Syu figlet toilet``` doesn't find the packages.

**Comment by Daandelange** [comment]
Thanks for testing !

No, `figlet` or `toilet` are 100% optional, weirdly an error is displayed, but the fallback works. (`Project: Mosaic` instead of ASCII banner `Mosaic`, nothing more).
On Unix systems, I redirect the output of the commands to `/dev/null` to hide errors, I think this doesn't work on M$ systems...

Regarding the broken table columns, it looks like the latest changes that adapt the column width to the terminal width broke it, needing the `bc` command to floor float calculations. From what I understand, `bc` is part of GNU, not bash, and there are different bash environments on Windows, GitBash being very minimal (are you using this?). `bc` could be installed, but `awk` which seems more universal, could you try this ? Daandelange/ofxAddonTool@5286e9b
Edit: Newer commits available, everything in your screenshot should be fixed now.

**Comment by d3cod3** [comment]
Yes, your commit fixed the issue on MSYS2, great!

Before trying it, i've installed bc:

```bash
pacman -Syu bc
```

and it solved the issue

![Sin título](https://user-images.githubusercontent.com/141075/95223088-79675b80-07f9-11eb-9e81-0b5ffb7509f0.jpeg)


But it's probably better to use awk, less instructions for the users

**Comment by Daandelange** [comment]
Ok, great. Did the "figlet/toilet command not found" messages go away too ?
There also seems to be a bug when addons are on a detached head.... there's a possible fix in new commit.

**Comment by Daandelange** [comment]
Closing this, as it seems to be working. For further issues we can always open issues in the submodule repo :)
