### ISSUE TITLE
Consider sending any useful changes upstream

### ISSUE THREAD

**Issue by danomatika** [d3cod3/Mosaic#37]
*I figure creating a single issue here is faster.*

Howdy, nice project.

I see you needed to fork some of my addons: ofxGLEditor, ofxLua, ofxMidi. If you have the time, please consider porting required changes upstream via PRs etc and we can work towards having the project build without needing forks.

**Comment by d3cod3** [comment]
Thanks and of course!

I'll check the code, clean it a little and push PRs to the respective addons.

ofxMidi was forked just in case, but i haven't changed anything, so i will switch to the original one in the readmes and in the Mosaic installer scripts.

ofxGLEditor just opened a PR with the only changes in my fork, a simple compile fix.

ofxLua is a little bit tricky, my fork is actually old ( from 2018 ) so i'll need to check your last code, and adapt my commits to create a proper PR. I'm away from work right now, so i'll do this when i'll be back in November.

**Comment by d3cod3** [comment]
Just updated references for ofxGLEditor and ofxMidi on READMEs and scripts, i'll work next week on ofxLua.

**Comment by d3cod3** [comment]
Just updated to your original repo of ofxLua, so no forks anymore!
