### ISSUE TITLE
Crashes when trying to add oscillator

### ISSUE THREAD

**Issue by anellus** [d3cod3/Mosaic#38]
Using windows 7, it crashes when I try to add an oscillator, it also crashes when I try to open the example file PD_SquareWaveOscillator.xml.

**Comment by d3cod3** [comment]
Did you download the last [windows release](https://github.com/d3cod3/Mosaic/releases/download/0.4.4/Mosaic_v0.4.4_windows_release.zip)? Or did you compiled Mosaic with the [installer](https://github.com/d3cod3/Mosaic-Installer)?

Anyway, right now windows release is highly buggy and needs a lot of testing, i didn't have or use windows systems and opengl do not works ( or do not works properly ) on virtual machines, so the road to a windows production release will be a long one...

Said that, Mosaic in windows comes with audio objects disabled as the DSP, so you can test everything except audio objects, as oscillators or everything sound related ( the PD_SquareWaveOscillator example is full of sound objects ).

I highly recommend you to install some linux as secondary OS ( the Mosaic installer will work automatically with Ubuntu, Debian, Mint, Fedora y arch Linux  ) and try Mosaic there

**Comment by anellus** [comment]
I used the last windows release.
