### ISSUE TITLE
Error in linux mint

### ISSUE THREAD

**Issue by janebeta7** [d3cod3/Mosaic#4]
when i execute install_mosaic_ubuntu i have this error

**/opt/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:352: fallo en las instrucciones para el objetivo '/opt/openFrameworks/addons/obj/linux64/Release/ofxPoco/src/ofxXmlPoco.o'
make[1]: *** [/opt/openFrameworks/addons/obj/linux64/Release/ofxPoco/src/ofxXmlPoco.o] Error 1
make[1]: *** Se espera a que terminen otras tareas....
make[1]: *** wait: No hay ningún proceso hijo.  Alto.
/opt/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:124: fallo en las instrucciones para el objetivo 'Release'
make: *** [Release] Error 2
"make -j$NUMPU Release" command failed with exit code 2.**

this is my lsb_relase -a
Distributor ID:	LinuxMint
Description:	Linux Mint 18.3 Sylvia
Release:	18.3
Codename:	sylvia

thanks!
Alba

**Comment by d3cod3** [comment]
Please try again this one:

https://gist.github.com/d3cod3/d1a544e0cf21b8733b567a3d87905d23

is the one adapted for Linux Mint. I've just revised and updated the script, please let me know.

**Comment by ferhoyo** [comment]
Distributor ID:	LinuxMint
Description:	Linux Mint 19.1 Tessa
Release:	19.1
Codename:	tessa

Got error:
`Unable to locate package librtaudio4
"apt install git curl wget libpoco-dev libpython2.7-dev libcurl3 librtaudio4 libjack0 libjack-jackd2-dev" command failed with exit code 100.`

I hacked your script to add the library versions that are in the repository
 line 42 from
`apt install git curl wget libpoco-dev libpython2.7-dev libcurl3 librtaudio4 libjack0 libjack-jackd2-dev`

to
`apt install git curl wget libpoco-dev libpython2.7-dev libcurl4 librtaudio6 libjack-jackd2-0 libjack-jackd2-dev`

With the above, the script installs OF and its addons, but I got the following error with Mosaic:

'Clonando en 'Mosaic'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (12/12), done.
remote:nTotalj1456:(delta(2),3reused,81(deltaM2),|pack-reusedB1442
Recibiendo objetos: 100% (1456/1456), 153.72 MiB | 1014.00 KiB/s, listo.
Resolviendo deltas: 100% (795/795), listo.
Revisando archivos: 100% (244/244), listo.
HOST_OS=Linux
checking pkg-config libraries:	 cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal libcurl rtaudio libpulse-simple alsa gl glu glew gtk+-3.0
with PKG_CONFIG_LIBDIR=
Package gstreamer-app-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-app-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gstreamer-app-1.0' found
Package gstreamer-app-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-app-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gstreamer-app-1.0' found
/opt/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/config.shared.mk:291: *** couldn't find gstreamer-app-1.0 pkg-config package or it's dependencies, did you run the latest install_dependencies.sh?.  Alto.
"make -j$NUMPU Release" command failed with exit code 2.`

I don't know how to go around this

**Comment by d3cod3** [comment]
I've just updated the linux mint script, fixed dependencies and switched to OF official release, due to various compile problems related with the github master branch.
Please try it and let me know!

**Comment by d3cod3** [comment]
Just uploaded last revision of the script. Tested on clean linux mint docker container. Should work now!
