### ISSUE TITLE
Slack Community Invite Link

### ISSUE THREAD

**Issue by ghost** [d3cod3/Mosaic#42]
Hello and good evening!

This is one of the best projects I've seen in the last couple of years for AV live performance. I want to be part of the community and if possible contribute, but can't manage to get an invite link to the slack workspace. The one on the README is the right one?

Thanks in advance

**Comment by Daandelange** [comment]
Hey, and welcome. :) 
There's no Slack channel that I'm aware of for Mosaic (there's indeed one in the readme!), but @d3cod3 started setting up a Discord server recently. There's also a forum on the way.
@d3cod3, what's the current state of these ?

**Comment by ghost** [comment]
Thank you @Daandelange. This is amazing, good to see this project getting more and more traction. If you can point the links when ready I'd love to be part of the community. Also, it is really interesting to build an API and future modules and the documentation is getting really good.

**Comment by d3cod3** [comment]
Hey guys, sorry for the delay, first of all thanks @luisArandas for your interest in Mosaic, then about the current state of community tools, as @Daandelange said, we have a discord server, here the invite:

https://discord.com/invite/sPJr6EEpyG

And the discourse forum it's up and running too, but empty right now, i didn't had time yet to give it the jumpstart ( create categories, create first basic posts, faqs, etc... ), you can check it and register here:

[Mosaic Forum](https://mosaicforum.cryptoriot.art/)

The slack link you found was an old channel i use at the beginning of Mosaic, but it's not active anymore, so thanks for remind me to remove it from the readme!

Anyway, i'm planning to speed up a little the community stuff the next months, so any help will be really appreciated!!!
Feel free to write me an email with your ideas and/or suggestions about Mosaic and we'll organize some meetings in discord first and later on the forum, to start giving that a little life.

Thanks again, i hope we'll talk soon

**Comment by ghost** [comment]
Thank you for that! 

Just joined the Discord server and registered in the forum right away. 

I am happy to see this project taking off and thinking about the future. We can talk on the server if you prefer @d3cod3  as well as on the forum and eventually arrange a meeting! 

See you soon!
