### ISSUE TITLE
Mosaic windows 0.5.0 is linked against opencv 452 while distributes with 440

### ISSUE THREAD

**Issue by seleniel** [d3cod3/Mosaic#47]
Hi!

the code execution cannot procees because libopencv_imgproc452.dll was not found. Reinstalling the program may fix this problem 
(of course it cannot ;))

thanks!
I.

**Comment by d3cod3** [comment]
Hi, you're right, of course it cannot!!

i'll fix the issues as soon as i'll be around a windows machine, but for now i will suggest to use the mosaic windows installer:

https://github.com/d3cod3/Mosaic-Installer

you'll find in that repo the instruction to compile Mosaic in your windows machine

In case you're not confortable with compiling and script stuff, then i'll write here when the issues will be solved.

cheers!

**Comment by WannaBeKratos** [comment]
Hi @d3cod3, I'm having the same issue with 0.5.0 on Windows 11 and 0.4.9 starts but then immediately
closes, I'm not having a lot of luck.
Have you fixed this problem already? 
I'm not familiar with c++ yet, else I would love to contribute to this project.
Greetings

**Comment by d3cod3** [comment]
Hi, sorry for the delay, here a .zip with the opencv452 libs:

[libopencv_core452.zip](https://github.com/d3cod3/Mosaic/files/7627375/libopencv_core452.zip)

I'll upload the full dlls to the last release, here:

https://github.com/d3cod3/Mosaic/releases/tag/0.5.0

thanks for remind me of the issue!

**Comment by WannaBeKratos** [comment]
Hi @d3cod3, thank you for replaying so quickly. 👍🏿 
I downloaded the DLL and added them to the v0.5.0 folder.
Now I get another error: 
![image](https://user-images.githubusercontent.com/77170000/144108182-95512873-c21f-4f9d-a202-dc1812bb0d39.png)
Followed by :
![image](https://user-images.githubusercontent.com/77170000/144108429-38e8dd3a-319a-4fbc-af17-79ac37c77746.png)
Do you think it is a Windows 11 problem ?

**Comment by d3cod3** [comment]
First, try using this dlls pack:

https://github.com/d3cod3/Mosaic/releases/download/0.5.0/v0.5.0_windows_dlls.zip

overwrite everything and try again, finger crossed!

In windows 10 there was no problem running it, but i can't answer your question, i'm not used to windows...

**Comment by WannaBeKratos** [comment]
Thanks! It works now except for it closing immediately, 
but that is a Windows 11 problem. The Linux version works great, so I will use that.
Cheers

**Comment by moebiussurfing** [comment]
> First, try using this dlls pack:
> 
> https://github.com/d3cod3/Mosaic/releases/download/0.5.0/v0.5.0_windows_dlls.zip
> 
> overwrite everything and try again, finger crossed!
> 
> In windows 10 there was no problem running it, but i can't answer your question, i'm not used to windows...

Thanks

I tried replacing all these dll zipped files,
and I can confirm it works here on Windows 10.

So I think you can pack a new zip here 
https://github.com/d3cod3/Mosaic/releases/download/0.5.0/Mosaic_v0.5.0_windows_release.zip

**Comment by d3cod3** [comment]
Thanks for testing it!

just uploaded the dll fixed windows release
