### ISSUE TITLE
Mosaic crashes on Mac with example files

### ISSUE THREAD

**Issue by myreauks** [d3cod3/Mosaic#48]
Hi!

I was going through the examples to explore the capabilities of your software. I tried the example projects one by one, and found the software crashing each time I tried to open an example after having opened one already. Moreover, the example haarTracking crashes immediately when loading even if there is no other example already open.

Mosaic 0.5.0
macOS 11.5.2
MacBook Pro 16" 2019

Btw, this is great initiative! I hope you keep developing Mosaic, it shows great promise!

**Comment by d3cod3** [comment]
Hi, thanks for the debug, i know, we need to solve some issues with the examples and the reloads routines, it happens on different OS, not just on osx

but anyway, thanks for your interest in the project, i'll let you know here when the related issues will be solved!

**Comment by fr4b3lo** [comment]
Exactly, on linux also happen this.

**Comment by d3cod3** [comment]
Soon will be available the last release of Mosaic, a lot more stable, with all the issues related with patches and examples loading resolved, stay alert, soon more info...
