### ISSUE TITLE
Ubuntu compile issues

### ISSUE THREAD

**Issue by mwolfeu** [d3cod3/Mosaic#51]
I ran into tonnes of issues while making/running myApps/Mosaic.   My fixes are below.  It got me to a running binary.  No idea how stable it is.

OFx: of_v0.11.2_linux64gcc6_release
Ubuntu: 20.04

Issue
When linking you get the error: execvp: /bin/sh: Argument list too long
Description
Posix sh command length at compile time is too short for make.  Literally the paths in the command are too long. Keep them as short as possible
Immediate hack
mv very long path to/of_v0.11.2_linux64gcc6_release ~/of
rerun the OFx compile script
Solution
Use distributed make files for each addon instead of adding EVERYTHING to the final link.

Issue
ofxHapPlayer can't find dispatch.h
Solution (should be documented on main README.md)
sudo apt-get install libsnappy-dev libswresample-dev libavcodec-dev libavformat-dev libdispatch-dev

Issue
ofxAudioAnalyzer does not include linux fftw lib.
Hack
mkdir fftw
cd fftw
wget https://www.fftw.org/fftw-3.3.10.tar.gz
tar -xf ff*
cd fftw-3.3.10/
./configure --prefix /tmp/FFT/ --enable-float
make
mkdir ~/of/addons/ofxAudioAnalyzer/libs/fftw3f/lib/linux64
cp .libs/libfftw3f.a ~/of/addons/ofxAudioAnalyzer/libs/fftw3f/lib/linux64
Solution
Linux libs should be included

Issue
make run returns
./Mosaic: error while loading shared libraries: libndi.so.3: cannot open shared object file: No such file or directory
Hack
Before running from command line:
export LD_LIBRARY_PATH=~/of/addons/ofxNDI/libs/libndi/lib/x86_64-linux-gnu
then:
make run
Solution
Fix makefile

Hope it helps!

**Comment by d3cod3** [comment]
Hi, thanks for your effort and suggestion!

Just check this:

https://github.com/d3cod3/Mosaic-Installer

there's the Mosaic installer script with some of your fixes already solved, and it works out of the box on fresh ubuntu 20.04 install

As it's recommended on the README, everything it's tested right now with of_v11.0, not of_v11.2 as in your case, but probably that shouldn't be an issue.

Can you provide some basic example about the distributed make files for the addons? It would be really helpful!

Thanks again!

**Comment by mwolfeu** [comment]
Just did a quick check on a few dev websites to make sure I didn't steer you wrong.  The best solution for gmake is the solution here:
https://unix.stackexchange.com/questions/480685/argument-list-too-long-error-with-makefile

Ubuntu and Xcode use gmake so this shouldn't be a problem.  I don't know about cmake/windows.

My original suggestion using distributed/nested/recursive makefiles seems to have its own complications:
https://stackoverflow.com/questions/724058/creating-nested-makefile
