### ISSUE TITLE
Instant crash on launch

### ISSUE THREAD

**Issue by statixVFX** [d3cod3/Mosaic#52]
macOS Monterey 12.3.1 Macbook Air m1

Did as the suggested install. Crashes instantly on launch Got this crash report:

It mentions missing the python2.7 libs, are they not included?

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Mosaic [14046]
Path:                  /Applications/Mosaic.app/Contents/MacOS/Mosaic
Identifier:            org.example.Mosaic
Version:               1.0 (1.0.0)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-04-09 17:27:50.9539 +0200
OS Version:            macOS 12.3.1 (21E258)
Report Version:        12
Anonymous UUID:        499C54A1-8402-64EB-15B2-98B227B0892B

Sleep/Wake UUID:       D72FA654-D6C3-4397-98CD-0FD34EE055F4

Time Awake Since Boot: 130000 seconds
Time Since Wake:       5051 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /System/Library/Frameworks/Python.framework/Versions/2.7/Python
Referenced from: /Applications/Mosaic.app/Contents/MacOS/Mosaic
Reason: tried: '/System/Library/Frameworks/Python.framework/Versions/2.7/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/2.7/Python' (no such file)
(terminated at launch; ignore backtrace)

Application Specific Information:
Library not loaded: /System/Library/Frameworks/Python.framework/Versions/2.7/Python
Referenced from: /Applications/Mosaic.app/Contents/MacOS/Mosaic
Reason: tried: '/System/Library/Frameworks/Python.framework/Versions/2.7/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/2.7/Python' (no such file)

Kernel Triage:
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage

Thread 0 Crashed:
0   Rosetta Runtime Routines	       0x107332940 ???
1   <translation info unavailable>	       0x10738718c ???
2   dyld                          	       0x203d7c212 abort_with_payload_wrapper_internal + 80
3   dyld                          	       0x203d7c244 abort_with_payload + 9
4   dyld                          	       0x203d2a76f dyld4::halt(char const*) + 375
5   dyld                          	       0x203d265a5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3995
6   dyld                          	       0x203d254d4 start + 388

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffdde9a4 0x7ff7ffdda000 + 18852
1   runtime                       	    0x7ff7ffdec738 0x7ff7ffdda000 + 75576
2   runtime                       	    0x7ff7ffdeded0 0x7ff7ffdda000 + 81616

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x00000003081f4a90   x3: 0x0000000000000083
    x4: 0x00000003081f4690   x5: 0x0000000000000000   x6: 0x2a0501082a041508   x7: 0x0000002052baa309
    x8: 0x00000003081f4690   x9: 0x0000000000000000  x10: 0x0000000000000083  x11: 0x00000003081f4690
   x12: 0x0000000000000083  x13: 0x00000003081f4a90  x14: 0x0000000000000001  x15: 0x0000000000000006
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x800000010f39bb70  x19: 0x0000000107328000
   x20: 0x00000000000007ff  x21: 0x000000010f3a0fa0  x22: 0xffffffffffffffff  x23: 0x0000000107332914
   x24: 0x0000000203d7c212  x25: 0x00000001073321f4  x26: 0x00000001073859b0  x27: 0x0000000000000000
   x28: 0x0000000203d660de   fp: 0x000000002c000000   lr: 0x000000010738718c
    sp: 0x000000010f39bb70   pc: 0x0000000107332940 cpsr: 0x80001000
   far: 0x0000000107387000  esr: 0x56000080  Address size fault

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x203d20000 -        0x203d8bfff dyld (*) <dd9e80de-fb3b-349b-96a4-46874ad34d11> /usr/lib/dyld
    0x7ff7ffdda000 -     0x7ff7ffe09fff runtime (*) <24497be3-a1b4-360a-b90e-cde9ce78a93b> /usr/libexec/rosetta/runtime

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=57.3M resident=0K(0%) swapped_out_or_unallocated=57.3M(100%)
Writable regions: Total=160.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=160.7M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Rosetta Arena                     4096K        2 
Rosetta Generic                    784K      193 
Rosetta IndirectBranch              32K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                20K        2 
Rosetta Thread Context              20K        2 
Stack                             8176K        1 
Stack Guard                       56.0M        1 
VM_ALLOCATE                       13.3M        5 
VM_ALLOCATE (reserved)             124K        9         reserved VM address space (unallocated)
__DATA                            8504K       19 
__DATA_CONST                        80K        1 
__LINKEDIT                        11.5M       15 
__TEXT                            45.9M       12 
dyld private memory               1024K        1 
mapped file                        6.1G       52 
===========                     =======  ======= 
TOTAL                              6.4G      317 
TOTAL, minus reserved VM space     6.4G      317 

-----------
Full Report
-----------

{"app_name":"Mosaic","timestamp":"2022-04-09 17:27:51.00 +0200","app_version":"1.0","slice_uuid":"e793eaef-9778-3b27-97cd-c7b330fb61cf","build_version":"1.0.0","platform":1,"bundleID":"org.example.Mosaic","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.3.1 (21E258)","incident_id":"884A0748-522C-4BF6-9088-8D7E007B5215","name":"Mosaic"}
{
  "uptime" : 130000,
  "procLaunch" : "2022-04-09 17:27:50.7102 +0200",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "procStartAbsTime" : 3337026549396,
  "coalitionID" : 25944,
  "osVersion" : {
    "train" : "macOS 12.3.1",
    "build" : "21E258",
    "releaseType" : "User"
  },
  "captureTime" : "2022-04-09 17:27:50.9539 +0200",
  "incident" : "884A0748-522C-4BF6-9088-8D7E007B5215",
  "bug_type" : "309",
  "pid" : 14046,
  "procExitAbsTime" : 3337028007065,
  "translated" : true,
  "cpuType" : "X86-64",
  "procName" : "Mosaic",
  "procPath" : "\/Applications\/Mosaic.app\/Contents\/MacOS\/Mosaic",
  "bundleInfo" : {"CFBundleShortVersionString":"1.0","CFBundleVersion":"1.0.0","CFBundleIdentifier":"org.example.Mosaic"},
  "storeInfo" : {"deviceIdentifierForVendor":"94EBC253-CAD5-53F9-BD03-1C9D4572DC19","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.example.Mosaic",
  "crashReporterKey" : "499C54A1-8402-64EB-15B2-98B227B0892B",
  "wakeTime" : 5051,
  "sleepWakeUUID" : "D72FA654-D6C3-4397-98CD-0FD34EE055F4",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: \/System\/Library\/Frameworks\/Python.framework\/Versions\/2.7\/Python","Referenced from: \/Applications\/Mosaic.app\/Contents\/MacOS\/Mosaic","Reason: tried: '\/System\/Library\/Frameworks\/Python.framework\/Versions\/2.7\/Python' (no such file), '\/Library\/Frameworks\/Python.framework\/Versions\/2.7\/Python' (no such file)"]},
  "ktriageinfo" : "VM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\n",
  "asi" : {"dyld":["Library not loaded: \/System\/Library\/Frameworks\/Python.framework\/Versions\/2.7\/Python","Referenced from: \/Applications\/Mosaic.app\/Contents\/MacOS\/Mosaic","Reason: tried: '\/System\/Library\/Frameworks\/Python.framework\/Versions\/2.7\/Python' (no such file), '\/Library\/Frameworks\/Python.framework\/Versions\/2.7\/Python' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":1722072,"threadState":{"x":[{"value":6},{"value":1},{"value":13021170320},{"value":131},{"value":13021169296},{"value":0},{"value":3027827459052803336},{"value":138826916617},{"value":13021169296},{"value":0},{"value":131},{"value":13021169296},{"value":131},{"value":13021170320},{"value":1},{"value":6},{"value":521},{"value":0},{"value":9223372041405184880},{"value":4415717376},{"value":2047},{"value":4550430624},{"value":18446744073709551615},{"value":4415760660},{"value":8654406162,"symbolLocation":80,"symbol":"abort_with_payload_wrapper_internal"},{"value":4415758836},{"value":4416100784},{"value":0},{"value":8654315742,"symbolLocation":10,"symbol":"__abort_with_payload"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4416106892},"cpsr":{"value":2147487744},"fp":{"value":738197504},"sp":{"value":4550409072},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4415760704,"matchesCrashFrame":1},"far":{"value":4416106496}},"frames":[{"imageOffset":4415760704,"region":"Rosetta Runtime Routines","symbolLocation":10560,"imageIndex":0},{"imageOffset":4416106892,"region":"<translation info unavailable>","imageIndex":0},{"imageOffset":377362,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":1},{"imageOffset":377412,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":1},{"imageOffset":42863,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":1},{"imageOffset":26021,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3995,"imageIndex":1},{"imageOffset":21716,"symbol":"start","symbolLocation":388,"imageIndex":1}]},{"id":1722092,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18852,"imageIndex":2},{"imageOffset":75576,"imageIndex":2},{"imageOffset":81616,"imageIndex":2}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8654028800,
    "size" : 442368,
    "uuid" : "dd9e80de-fb3b-349b-96a4-46874ad34d11",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703126364160,
    "size" : 196608,
    "uuid" : "24497be3-a1b4-360a-b90e-cde9ce78a93b",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  }
],
  "sharedCache" : {
  "base" : 140703454347264,
  "size" : 15226814464,
  "uuid" : "a1c5d735-ceb0-350d-9729-bb0e9be86d75"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=57.3M resident=0K(0%) swapped_out_or_unallocated=57.3M(100%)\nWritable regions: Total=160.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=160.7M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nRosetta Arena                     4096K        2 \nRosetta Generic                    784K      193 \nRosetta IndirectBranch              32K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                20K        2 \nRosetta Thread Context              20K        2 \nStack                             8176K        1 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                       13.3M        5 \nVM_ALLOCATE (reserved)             124K        9         reserved VM address space (unallocated)\n__DATA                            8504K       19 \n__DATA_CONST                        80K        1 \n__LINKEDIT                        11.5M       15 \n__TEXT                            45.9M       12 \ndyld private memory               1024K        1 \nmapped file                        6.1G       52 \n===========                     =======  ======= \nTOTAL                              6.4G      317 \nTOTAL, minus reserved VM space     6.4G      317 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60356660bbe37970735c5624",
      "factorPackIds" : {

      },
      "deploymentId" : 240000027
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000132
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookAir10,1, BootROM 7459.101.3, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Display: Acer T272HUL, 2560 x 1440 (QHD/WQHD - Wide Quad High Definition), MirrorOff, Online
Memory Module: LPDDR4
AirPort: Wi-Fi, wl0: Feb  8 2022 01:44:45 version 18.60.21.0.7.8.126 FWID 01-1cdae627
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: USB 10/100/1000 LAN, Ethernet, en5
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB3.0 Hub
USB Device: USB2.0 Hub
USB Device: USB 2.0 BILLBOARD
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.
`

**Comment by d3cod3** [comment]
Hi, thanks for the report, and yes, it's an issue related with python2, removed from OSX in the Monterrey release

```Library not loaded: /System/Library/Frameworks/Python.framework/Versions/2.7/Python```

To solve the issue you'll need to copy Python.framework ( version 2.7 ) into /System/Library/Frameworks/

Here a link for downloading it:

[Python.framework.zip](https://www.d3cod3.org/downloads/Python.framework.zip)

We tested Mosaic on a new M1 macbook pro with macOS Monterrey and it's working fine!

**Comment by statixVFX** [comment]
Many thanks! I did install it from official sources and it seems to be running! 
https://www.python.org/downloads/release/python-2718/

Very much looking forward to diving deep into Mosaic, thanks so much for creating and sharing this tool :)

**Comment by d3cod3** [comment]
You're welcome!
