### ISSUE TITLE
No sound menu on Windows 10 ...

### ISSUE THREAD

**Issue by moebiussurfing** [d3cod3/Mosaic#56]
Hello,
I downloaded the binary and  replaced the dlls zip from other issue.
![mosaic](https://user-images.githubusercontent.com/2106149/172082742-1f8d6d25-9ea3-4e50-a7b7-baa210a9346b.PNG)
![mosaic2](https://user-images.githubusercontent.com/2106149/172082743-b256445c-b3cb-434a-bd1e-4b7f826b2022.PNG)

**Comment by d3cod3** [comment]
Yes, in windows we don't have 100% of developed Mosaic, the sound engine based on ofxPDSP still have stability problems in windows, so it's deactivated there
