### ISSUE TITLE
[WSL] bwrap: kernel does not support user namespaces

### ISSUE THREAD

**Issue by antoineL** [d3cod3/Mosaic#57]
I tried to install Mosaic on WSL2/Ubuntu20.04. Install went relatively smoothly: the only error I saw was while flatpak installed `org.freedesktop.Platform.openh264` (I think), when I got
```
Warning: While trying to apply extra data: apply_extra script failed, exit status 256
``` 
Trying to run mosaic, I got
```
antoineL@MyPC:~$ flatpak run org.d3cod3.Mosaic
bwrap: Creating new namespace failed, likely because the kernel does not support user namespaces.  bwrap must be installed setuid on such systems.
error: ldconfig failed, exit status 256
```
It seems this particular issue is (somewhat) known elsewhere: cf. [opam#3747](https://github.com/ocaml/opam/issues/3747) which points to OCaml (and `bwrap` is [bubblewrap](https://github.com/containers/bubblewrap); with issue [#272](https://github.com/containers/bubblewrap/issues/272) open since 2018).
These reports are dated mainly from 2018-19, and WSL is a relatively fast-moving target.
StackOverflow also has a [question](https://stackoverflow.com/questions/54987110) about it; there is even a 2020 [answer](https://stackoverflow.com/a/62012289) which looks like promising: it leads to [Jane Street Install OCaml repo](https://github.com/janestreet/install-ocaml); however I cannot saw anything interesting there, looks like a dead end to me.

I am a complete newbie to Mosaic and fastpak, so I cannot attempt to locate where OCaml and/or odap are involved (perhaps this issue belongs to [Mosaic-installer](https://github.com/d3cod3/Mosaic-Installer)? Or even flatpak?), much less propose a path for a solution. But perhaps others might take a look and give useful hints, or perhaps workarounds?

**Comment by d3cod3** [comment]
Hi antoineL,

i'm sorry but this issue is completely out of the bounds of Mosaic basecode, but thanks a lot for all the detailed info anyway, i will let you know if some solution appears!
