### ISSUE TITLE
Settings or options for GUI / font sizes?

### ISSUE THREAD

**Issue by RKelln** [d3cod3/Mosaic#59]
Are there any options to change the GUI and/or font sizes? Environment variable I can set? (For a HiDPI screen in linux [Ubuntu]).

Thanks!

**Comment by d3cod3** [comment]
Can you post some screenshot, just to have a visual of the situation with HiDPI?

Right now there is not this option available, but it would be not hard to add, please send some screenshots, thanks!

**Comment by RKelln** [comment]
Sure this is the screen at my normal settings (which are a bit weird: 2256x1504 at 125% scaling)

![image](https://user-images.githubusercontent.com/63819/212083246-54ac6d1e-126f-4015-ae03-64d674f0d647.png)

If I do no OS screen scaling its a bit more readable since the fonts are crisper but really tiny:

![image](https://user-images.githubusercontent.com/63819/212086855-67864a6a-3e15-4d04-9be6-b5d711509ae1.png)

That res might be fine for performances (as you can zoom in and out and can scale fonts in code editor) but constructing the patches would be nicer with font scaling for sure.

**Comment by d3cod3** [comment]
Ok, i see, and yes, i usually work on hd screens 1920x1080, but for sure it's maybe too little on higher resolution screens.

I will check the difficulty of adding a general font scaling, or maybe automatically adapt depending on screen resolution, don't know yet, and we'll see.

I'll let you know if and when we'll implement it, as you're working with linux, when the new code will be uploaded to the repo, you'll just need to update the Mosaic and ofxVisualProgramming repos with a ```git pull``` and recompile again.

Thanks again!

**Comment by d3cod3** [comment]
Please check issue #77
