### ISSUE TITLE
Mosaic still running after closing using window X in Ubuntu

### ISSUE THREAD

**Issue by RKelln** [d3cod3/Mosaic#60]
Mosaic is still running after closing using the window chrome X in the top right. I.E
```
/opt/openFrameworks/apps/d3cod3/Mosaic/bin/Mosaic
```
is in my process list.

Using File > Quit works as expected.

Ubuntu 22.04.

**Comment by d3cod3** [comment]
Yes, that's a perks of openFrameworks, you can close it with File > Quit, or with ctrl-q
