### ISSUE TITLE
Version 0.6.5_ofximgui_next does not render the UI properly.

### ISSUE THREAD

**Issue by megabitsenmzq** [d3cod3/Mosaic#67]
The menu size looks too large, and node UI elements are offset.

<img width="2028" alt="image" src="https://user-images.githubusercontent.com/5499507/229487181-a1140f3a-5f54-4deb-86a4-44109447a042.png">

[0.6.5_ofximgui_next](https://github.com/d3cod3/Mosaic/releases/tag/0.6.5_ofximgui_next)

**Comment by d3cod3** [comment]
Hey, thanks for testing it, can you give me some details about your screen resolution and mac model/year?

**Comment by megabitsenmzq** [comment]
I'm using an 2020 M1 Air. With an LG external 4K monitor. (3840 × 2160)

**Comment by d3cod3** [comment]
The ofximgui_next branch is currently in the works, it's better to use the stable version, i've just updated everything and published the 0.6.6. you'll find it in the releases.

let me know is it works properly
