### ISSUE TITLE
About this project

### ISSUE THREAD

**Issue by guohongbin2019** [d3cod3/Mosaic#7]
What application scenarios and functions are used in this project? Is there a detailed introduction?

**Comment by d3cod3** [comment]
Hi, the project is in alpha stage at the moment, a lot of stuff is yet to be fixed, cleaned and still a bunch of objects are still not implemented.

The date for the beta release will be between December 2019 and February 2020

That said, the main application scenarios are live-coding/live audiovisual performance, teaching and prototyping everything related with image, sound, real-time, data manipulation, connection with external hardware (midi, kinect, audio devices, dmx, arduino), communication via osc between computers or between other softwares, live-coding in Lua(with OF embedded for generative graphics), Python, Bash, live-patching with PureData and (not sure yet) live-coding with Java/Processing; everything embedded in a dataflow programming environment.

And no, right now there is not a proper detailed introduction, there is the official webpage (work in progress) with some documentation about the objects https://mosaic.d3cod3.org, and there is a slack project where a community is starting and everyone interested can ask me for an invite: 
https://mosaicprocess.slack.com/

A general simple introduction can be found in the README of the github repo (this one).

The project is growing fast, so docs are updated a lot.

Hope this helps!
