### ISSUE TITLE
VideoGraber crash Mosaic on Mint with OF(Mosaic)

### ISSUE THREAD

**Issue by fr4b3lo** [d3cod3/Mosaic#70]
When i install new OF from OF site works in OF. When i install OF from D3cod3 crash Videograber in Mosaic and OF. Old version works good.

[notice ] ofGstVideoGrabber: Probing devices with udev...
[notice ] ofGstVideoGrabber: Found device 0c45:6366, getting capabilities...
[notice ] ofGstVideoGrabber: detected v4l2 device: USB 2.0 Camera: USB Camera
[notice ] ofGstVideoGrabber: driver: uvcvideo, version: 331607
[notice ] ofGstVideoGrabber: Capabilities: 0x84A00001
[notice ] ofGstVideoGrabber: Found device 0c45:6366, getting capabilities...
[notice ] ofGstVideoGrabber: detected v4l2 device: USB 2.0 Camera: USB Camera
[notice ] ofGstVideoGrabber: driver: uvcvideo, version: 331607
[notice ] ofGstVideoGrabber: Capabilities: 0x84A00001
[notice ] device /dev/video1 seems to not have the capture capability, (radio tuner/metadata device?)
[notice ] removing it from device list
[notice ] 0: USB 2.0 Camera: USB Camera
[notice ] ofGstVideoGrabber: initGrabber(): selected device: USB 2.0 Camera: USB Camera
[notice ] ofGstVideoGrabber: initGrabber(): selected format: 320x240 image/jpeg  framerate: 30/1
[notice ] ofGstUtils: setPipelineWithSink(): gstreamer pipeline: v4l2src name=video_source device=/dev/video0 ! image/jpeg,width=320,height=240,framerate=30/1 ! decodebin  ! videoconvert   ! appsink name=ofappsink enable-last-sample=0 caps="video/x-raw, format=RGB, width=320, height=240"
Segmentation fault (core dumped)
make: *** [/opt/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:184: run] Error 139

**Comment by d3cod3** [comment]
This is happening 99.9% due to this issue:

https://github.com/openframeworks/openFrameworks/issues/6871

In the linux PC i use to test Mosaic i modified the OF core code as they explain in the issue, so no problem there

I just tested in my linux laptop and i had exactly the same error as you when trying to open the webcam, i'm going to modify the OF core code and let you know is it solve the issue.

Just for clarifications, if you are using the Mosaic Installer:

https://github.com/d3cod3/Mosaic-Installer

the OF version is actually OK with Mosaic code is the of_v0.11.2_linux64gcc6_release.tar.gz, NOT the nighly builds! ( the nightly mess up a lot of ofxaddons stuff included with Mosaic )

**Comment by d3cod3** [comment]
Yes, exactly, this:

https://github.com/openframeworks/openFrameworks/commit/bd4042344dc9670770754374607d2ca8190f9476

fixes the issue

If you modify your OF core code as in this commit, recompile Mosaic and video grabber will work!

**Comment by fr4b3lo** [comment]
> This is happening 99.9% due to this issue:
> 
> [openframeworks/openFrameworks#6871](https://github.com/openframeworks/openFrameworks/issues/6871)
> 
> In the linux PC i use to test Mosaic i modified the OF core code as they explain in the issue, so no problem there
> 
> I just tested in my linux laptop and i had exactly the same error as you when trying to open the webcam, i'm going to modify the OF core code and let you know is it solve the issue.
> 
> Just for clarifications, if you are using the Mosaic Installer:
> 
> https://github.com/d3cod3/Mosaic-Installer

yes.

> 
> the OF version is actually OK with Mosaic coe is the of_v0.11.2_linux64gcc6_release.tar.gz, NOT the nighly builds! ( the nightly mess up a lot of ofxaddons stuff included with Mosaic )

ok, thanks

**Comment by fr4b3lo** [comment]
> Yes, exactly, this:
> 
> [openframeworks/openFrameworks@bd40423](https://github.com/openframeworks/openFrameworks/commit/bd4042344dc9670770754374607d2ca8190f9476)
> 
> fixes the issue
> 
> If you modify your OF core code as in this commit, recompile Mosaic and video grabber will work!

 i will try.

**Comment by fr4b3lo** [comment]
I managed modify OF code and Mosaic dont crash with videoGrabber. 
But keeps don't show the image only black image!!! 
In logger: red line ofGstVideoPlayer: alloccate() cannot get pippeline  caps
In ofGstVideoGrabber: dont has erros and detected usbvideocameraset 320x240
