### ISSUE TITLE
Error compiling 0.6.5 on Mint 21.2

### ISSUE THREAD

**Issue by fr4b3lo** [d3cod3/Mosaic#72]
opt/openFrameworks/addons/ofxVisualProgramming/src/core/IconsFontAwesome5.h:219:22: error: invalid conversion from ‘const char8_t*’ to ‘const char*’ [-fpermissive]
...
.h:370:24: error: invalid conversion from ‘const char8_t*’ to ‘const char*’ [-fpermissive]
...
.h:938:24: error: invalid conversion from ‘const char8_t*’ to ‘const char*’ [-fpermissive]
...
h:342:29: error: invalid conversion from ‘const char8_t*’ to ‘const char*’ [-fpermissive

...
/opt/openFrameworks/addons/ofxVisualProgramming/src/core/IconsFontAwesome5.h:915:27: error: invalid conversion from ‘const char8_t*’ to ‘const char*’ [-fpermissive]
...
/opt/openFrameworks/addons/ofxVisualProgramming/src/core/IconsFontAwesome5.h:874:26: error: invalid conversion from ‘const char8_t*’ to ‘const char*’ [-fpermissive]

/opt/openFrameworks/addons/ofxVisualProgramming/src/core/imgui_helpers.h:168:13: warning: ‘void ImGuiEx::HelpMarker(const char*)’ defined but not used [-Wunused-function]
  168 | static void HelpMarker(const char* desc){
      |             ^~~~~~~~~~
In file included from /opt/openFrameworks/addons/ofxImGui/src/ofxImGui.h:5,
                 from /opt/openFrameworks/addons/ofxVisualProgramming/src/ofxVisualProgramming.h:41,
                 from /opt/openFrameworks/apps/d3cod3/Mosaic/src/SplashScreen.cpp:34:
/opt/openFrameworks/addons/ofxImGui/src/ImHelpers.h:142:20: warning: ‘void* GetImTextureID(GLuint)’ defined but not used [-Wunused-function]
  142 | static ImTextureID GetImTextureID(GLuint glID)
      |                    ^~~~~~~~~~~~~~
/opt/openFrameworks/addons/ofxImGui/src/ImHelpers.h:136:20: warning: ‘void* GetImTextureID(const ofBaseHasTexture&)’ defined but not used [-Wunused-function]
  136 | static ImTextureID GetImTextureID(const ofBaseHasTexture& hasTexture)
      |                    ^~~~~~~~~~~~~~
make[1]: Leaving directory '/opt/openFrameworks/apps/d3cod3/Mosaic'
make: *** [/opt/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2

**Comment by d3cod3** [comment]
Just updated and published Mosaic 0.6.6

In linux boxes, when problems arise with the installer, it's better to use the flatpak release:

https://flathub.org/apps/org.d3cod3.Mosaic

Just updated to the last 0.6.6, one click install!
