### ISSUE TITLE
Mosaic flatpak 0.6.6 don't open on mint

### ISSUE THREAD

**Issue by fr4b3lo** [d3cod3/Mosaic#75]
Hello, installed new Mosaic version by software manager but the software dont open. On flatpak are installed ut when i try open nothing occurs.

**Comment by d3cod3** [comment]
Hi, i'll need some more info to answer something, you need to run this in your terminal:

```flatpak run org.d3cod3.Mosaic```

and post here the output error

**Comment by fr4b3lo** [comment]
Hello, man ...nothing appears. Only returns to the new prompt.

**Comment by d3cod3** [comment]
have you installed it with this command?

```flatpak install flathub org.d3cod3.Mosaic```

And have you previously installed Mosaic with flatpak?

maybe try to uninstall and reinstall it:

```flatpak uninstall org.d3cod3.Mosaic```

and then

```flatpak install org.d3cod3.Mosaic```

**Comment by d3cod3** [comment]
And check your OS, Mosaic flatpak release only supports x86_64 architecture

**Comment by fr4b3lo** [comment]
Hello, i installed with Flatpak linux link in Mosaic site. In central software says that its installed with the green button to launch it.  Older versions of Mosaic was installed in this machine and worked. Since 6.5 i had problems. Wanna try with this codes, thanks!

$ uname -m
x86_64

flatpak uninstall org.d3cod3.Mosaic

 1. [-] org.d3cod3.Mosaic               stable        r
 2. [-] org.d3cod3.Mosaic.Locale        stable        r

Uninstall complete.
____________________________________________________________________
flatpak install org.d3cod3.Mosaic
Looking for matches…
org.d3cod3.Mosaic permissions:
    ipc           network              pulseaudio      x11
    devices       file access [1]

 1. [✓] org.d3cod3.Mosaic.Locale         stable         i          flathub        170,1 kB / 6,5 MB
 2. [✓] org.d3cod3.Mosaic                stable         i          flathub          1,2 GB / 1,1 GB

Installation complete.
$ flatpak run org.d3cod3.Mosaic
$
 _________________________________________________
nothing yet :(

**Comment by yiids** [comment]
same problem on debian 11, tried uninstalling and reinstalling,  flatpak run org.d3cod3.Mosaic doesnt give any output

**Comment by d3cod3** [comment]
Just fixed and updated to flathub, tested and running fine now!

you just need to run:

```flatpak update org.d3cod3.Mosaic```

and 

```flatpak run org.d3cod3.Mosaic```

let me know if is working

cheers

**Comment by yiids** [comment]
for me its working, thanks!
