### ISSUE TITLE
segfault at run

### ISSUE THREAD

**Issue by yiids** [d3cod3/Mosaic#76]
Compiled from source on debian 11. 
segfaults immediately  on run. 
Stacktrace:
`     Timestamp: Thu 2023-10-05 12:53:22 CEST (3min 15s ago)
  Command Line: ./Mosaic
    Executable: /home/y/src/audiovisuals/of-0.11/apps/myApps/Mosaic/bin/Mosaic
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slice/vte-spawn-e0f7dec2-e7c2-409f-ad1c-be0ffa7052f6.scope
          Unit: user@1000.service
     User Unit: vte-spawn-e0f7dec2-e7c2-409f-ad1c-be0ffa7052f6.scope
         Slice: user-1000.slice
     Owner UID: 1000 (y)
       Boot ID: d6382a1522854834a9512f262243e387
    Machine ID: 27380db539cf46a49bea4736cea5a1b7
      Hostname: dell
       Storage: /var/lib/systemd/coredump/core.Mosaic.1000.d6382a1522854834a9512f262243e387.104235.1696503202000000.zst
       Message: Process 104235 (Mosaic) of user 1000 dumped core.
                
                Stack trace of thread 104301:
                #0  0x00007fabd2a09995 n/a (iHD_drv_video.so + 0x18a995)
                #1  0x00007fabd29fafdb n/a (iHD_drv_video.so + 0x17bfdb)
                #2  0x00007fabd29e1e15 n/a (iHD_drv_video.so + 0x162e15)
                #3  0x00007fabd2be5105 n/a (iHD_drv_video.so + 0x366105)
                #4  0x00007fabd2be959f n/a (iHD_drv_video.so + 0x36a59f)
                #5  0x00007fabd2be999e n/a (iHD_drv_video.so + 0x36a99e)
                #6  0x00007fabd2bb0be2 n/a (iHD_drv_video.so + 0x331be2)
                #7  0x00007fabe346417c vaPutImage (libva.so.2 + 0x717c)
                #8  0x00007fabe0381b7c n/a (libgstvaapi.so + 0x5fb7c)
                #9  0x00007fabe0340476 n/a (libgstvaapi.so + 0x1e476)
                #10 0x00007fabe03476ce n/a (libgstvaapi.so + 0x256ce)
                #11 0x00007fac010c14b3 n/a (libgstbase-1.0.so.0 + 0x494b3)
                #12 0x00007fac010c4e6d n/a (libgstbase-1.0.so.0 + 0x4ce6d)
                #13 0x00007fac00fbbe58 gst_pad_query (libgstreamer-1.0.so.0 + 0x8ce58)
                #14 0x00007fac00fbc5bb gst_pad_peer_query (libgstreamer-1.0.so.0 + 0x8d5bb)
                #15 0x00007fac00ffb648 gst_pad_peer_query_caps (libgstreamer-1.0.so.0 + 0xcc648)
                #16 0x00007fac010c4b4f n/a (libgstbase-1.0.so.0 + 0x4cb4f)
                #17 0x00007fac00fbbe58 gst_pad_query (libgstreamer-1.0.so.0 + 0x8ce58)
                #18 0x00007fac00fbc5bb gst_pad_peer_query (libgstreamer-1.0.so.0 + 0x8d5bb)
                #19 0x00007fac00ff5988 n/a (libgstreamer-1.0.so.0 + 0xc6988)
                #20 0x00007fac00fba7be gst_pad_forward (libgstreamer-1.0.so.0 + 0x8b7be)
                #21 0x00007fac00ff854a gst_pad_proxy_query_caps (libgstreamer-1.0.so.0 + 0xc954a)
                #22 0x00007fac00fba9e4 gst_pad_query_default (libgstreamer-1.0.so.0 + 0x8b9e4)
                #23 0x00007fac00fbbe58 gst_pad_query (libgstreamer-1.0.so.0 + 0x8ce58)
                #24 0x00007fac00fbc5bb gst_pad_peer_query (libgstreamer-1.0.so.0 + 0x8d5bb)
                #25 0x00007fac00ffb648 gst_pad_peer_query_caps (libgstreamer-1.0.so.0 + 0xcc648)
                #26 0x00007fac01147391 n/a (libgstvideo-1.0.so.0 + 0x4f391)
                #27 0x00007fabe033a024 n/a (libgstvaapi.so + 0x18024)
                #28 0x00007fac01135d76 n/a (libgstvideo-1.0.so.0 + 0x3dd76)
                #29 0x00007fac00fbbe58 gst_pad_query (libgstreamer-1.0.so.0 + 0x8ce58)
                #30 0x00007fac00ff8dd8 gst_pad_query_caps (libgstreamer-1.0.so.0 + 0xc9dd8)
                #31 0x00007fac01135fe1 n/a (libgstvideo-1.0.so.0 + 0x3dfe1)
                #32 0x00007fac00fbbe58 gst_pad_query (libgstreamer-1.0.so.0 + 0x8ce58)
                #33 0x00007fac00fbc5bb gst_pad_peer_query (libgstreamer-1.0.so.0 + 0x8d5bb)
                #34 0x00007fac00ff5920 n/a (libgstreamer-1.0.so.0 + 0xc6920)
                #35 0x00007fac00fba7be gst_pad_forward (libgstreamer-1.0.so.0 + 0x8b7be)
                #36 0x00007fac00ff838e gst_pad_proxy_query_accept_caps (libgstreamer-1.0.so.0 + 0xc938e)
                #37 0x00007fac00fbafbb gst_pad_query_default (libgstreamer-1.0.so.0 + 0x8bfbb)
                #38 0x00007fac00fbbe58 gst_pad_query (libgstreamer-1.0.so.0 + 0x8ce58)
                #39 0x00007fac00ffb828 gst_pad_query_accept_caps (libgstreamer-1.0.so.0 + 0xcc828)
                #40 0x00007fac00fb48da n/a (libgstreamer-1.0.so.0 + 0x858da)
                #41 0x00007fac00fbe7d5 gst_pad_send_event (libgstreamer-1.0.so.0 + 0x8f7d5)
                #42 0x00007fabe377a138 n/a (libgstplayback.so + 0xf138)
                #43 0x00007fac00fb3488 n/a (libgstreamer-1.0.so.0 + 0x84488)
                #44 0x00007fac00fb2ca0 n/a (libgstreamer-1.0.so.0 + 0x83ca0)
                #45 0x00007fac00fbf3c8 gst_pad_sticky_events_foreach (libgstreamer-1.0.so.0 + 0x903c8)
                #46 0x00007fabe37859df n/a (libgstplayback.so + 0x1a9df)
                #47 0x00007fabe37835d5 n/a (libgstplayback.so + 0x185d5)
                #48 0x00007fabe3784124 n/a (libgstplayback.so + 0x19124)
                #49 0x00007fabe37843ce n/a (libgstplayback.so + 0x193ce)
                #50 0x00007fac001190a2 g_closure_invoke (libgobject-2.0.so.0 + 0x140a2)
                #51 0x00007fac0012b413 n/a (libgobject-2.0.so.0 + 0x26413)
                #52 0x00007fac001316cf g_signal_emit_valist (libgobject-2.0.so.0 + 0x2c6cf)
                #53 0x00007fac00131c3f g_signal_emit (libgobject-2.0.so.0 + 0x2cc3f)
                #54 0x00007fac0011d804 n/a (libgobject-2.0.so.0 + 0x18804)
                #55 0x00007fac00f6ba54 n/a (libgstreamer-1.0.so.0 + 0x3ca54)
                #56 0x00007fac0011f7ca g_object_notify_by_pspec (libgobject-2.0.so.0 + 0x1a7ca)
                #57 0x00007fac00fb3397 n/a (libgstreamer-1.0.so.0 + 0x84397)
                #58 0x00007fac00fbe450 gst_pad_push_event (libgstreamer-1.0.so.0 + 0x8f450)
                #59 0x00007fac010c4428 n/a (libgstbase-1.0.so.0 + 0x4c428)
                #60 0x00007fac010c5a3a n/a (libgstbase-1.0.so.0 + 0x4da3a)
                #61 0x00007fabe3611176 n/a (libgstcoreelements.so + 0xc176)
                #62 0x00007fac00fb480c n/a (libgstreamer-1.0.so.0 + 0x8580c)
                #63 0x00007fac00fb4e8e n/a (libgstreamer-1.0.so.0 + 0x85e8e)
                
                Stack trace of thread 104238:
                #0  0x00007fabff2cb7b2 futex_wait_cancelable (libpthread.so.0 + 0xe7b2)
                #1  0x00007fabf91835db n/a (iris_dri.so + 0x4e75db)
                #2  0x00007fabf91830a7 n/a (iris_dri.so + 0x4e70a7)
                #3  0x00007fabff2c4ea7 start_thread (libpthread.so.0 + 0x7ea7)
                #4  0x00007fabfec35a2f __clone (libc.so.6 + 0xfba2f)
                
                Stack trace of thread 104237:
                #0  0x00007fabff2cb7b2 futex_wait_cancelable (libpthread.so.0 + 0xe7b2)
                #1  0x00007fabf91835db n/a (iris_dri.so + 0x4e75db)
                #2  0x00007fabf91830a7 n/a (iris_dri.so + 0x4e70a7)
                #3  0x00007fabff2c4ea7 start_thread (libpthread.so.0 + 0x7ea7)
                #4  0x00007fabfec35a2f __clone (libc.so.6 + 0xfba2f)
                
                Stack trace of thread 104235:
                #0  0x00007fabfec2ef29 syscall (libc.so.6 + 0xf4f29)
                #1  0x00007fac00077472 g_cond_wait_until (libglib-2.0.so.0 + 0xa3472)
                #2  0x00007fac00f941fc n/a (libgstreamer-1.0.so.0 + 0x651fc)
                #3  0x000055ddf66e9a32 n/a (/home/y/src/audiovisuals/of-0.11/apps/myApps/Mosaic/bin/Mosaic + 0xde8a32)
                #4  0x000055ddf6000000 n/a (/home/y/src/audiovisuals/of-0.11/apps/myApps/Mosaic/bin/Mosaic + 0x6ff000)
`

**Comment by d3cod3** [comment]
First of all, thank you for your testing!

After digging in the debugger, i've found that the problem is not Mosaic related, is some of OF issues with gstreamer libs version 1.20 ( apparently it should work downgrading the gstreamer release )

https://github.com/openframeworks/openFrameworks/issues/6871

https://forum.openframeworks.cc/t/segmentation-fault-on-examples-computer-vision-opencvexample/39508

I'm going to test some solutions, i'll update here when i'll find a good one!

**Comment by d3cod3** [comment]
Just fixed and updated in flathub, tested and now working fine!

you'll need to run:

```flatpak update org.d3cod3.Mosaic```

and 

```flatpak run org.d3cod3.Mosaic```
