### ISSUE TITLE
Flatpak version crashes when running CV examples

### ISSUE THREAD

**Issue by VrtXArt** [d3cod3/Mosaic#79]
when i try to run computer vision examples and some other examples the mosaic shuts down and on the terminal  no errors  are shown.

Via mosaic_installer, it shows up too many  ".h" missing files and some addons.
 I tryed to copy those ".h" files from flatpak mosiac and copy them to  the locations needed  along the installation process of the mosaic_installer.h but it still has some missing files
I am using ubuntu 22.4, i5 core 8th , dedicate vídeo Nvidia tx 50, 16Mb RAM, Dell notebook
Opencv 4 an gstreamer compatible, python 3

And i also tryed on ubuntu 20.4

**Comment by d3cod3** [comment]
Hi, right now visual programming examples are not 100% stable, depending on the os platform and other issues.

I just tried the Mosaic_installer script in a virtual machine ewith ubuntu 22.04 and it's working fine, please post some more datailed info about the error you are having.

You can re-try installing Mosaic this:

first uninstall the flatpak release
```
flatpak remove org.d3cod3.Mosaic
``` 

remove previous installation or failed installation of Mosaic
```
sudo rm -rf /opt/openframeworks
``` 

clone Mosaic_Installer repo
```
git clone https://github.com/d3cod3/Mosaic-Installer
``` 

then go to Mosaic_Installer folder and run the installer
```
cd Mosaic-Installer
sudo ./mosaic_installer.sh
```
Wait for the script to finish, then reboot

If everything went fine, you'll have now a master build of Mosaic in your system ( currently working at 0.6.9 pre-release )

**Comment by VrtXArt** [comment]
Hi. thank you for your reply!
i also trying on debian 12 and is going under the same errors. 
 i just did what you said. and these are the log in both OS:

first i did change the openframeworks source to "https://github.com/openframeworks/openFrameworks.git"  becouse the one in the script mosaic_install.sh "https://www.d3cod3.org/downloads/of_v0.12.0_linux64gcc6_release_Mosaic.tar.gz" is not found:

`% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 6 100 6 0 0 12 0 --:--:-- --:--:-- --:--:-- 12

Downloading openFrameworks version: of_v0.12.0_linux64gcc6_release_Mosaic
--2024-11-17 18:04:04-- https://www.d3cod3.org/downloads/of_v0.12.0_linux64gcc6_release_Mosaic.tar.gz
Resolvendo [www.d3cod3.org](http://www.d3cod3.org/) ([www.d3cod3.org](http://www.d3cod3.org/))... 185.66.41.163
Conectando-se a [www.d3cod3.org](http://www.d3cod3.org/) ([www.d3cod3.org)|185.66.41.163|:443](http://www.d3cod3.org)%7C185.66.41.163%7C:443)... conectado.
A requisição HTTP foi enviada, aguardando resposta... 404 Not Found
2024-11-17 18:04:08 ERRO 404: Not Found.

debian12stud@debian:~/Mosaic-Installer$`

than:

`/opt/openFrameworks/addons/ofxVisualProgramming/src/utils.h: In function ‘uint64_t devURandom()’:
/opt/openFrameworks/addons/ofxVisualProgramming/src/utils.h:193:5: error: ‘ifstream’ was not declared in this scope; did you mean ‘std::ifstream’?
  193 |     ifstream urandom("/dev/urandom",ios::in|ios::binary);
      |     ^~~~~~~~
/opt/openFrameworks/addons/ofxVisualProgramming/src/utils.h: In function ‘uint64_t devURandom()’:
/opt/openFrameworks/addons/ofxVisualProgramming/src/utils.h:193:5: error: ‘ifstream’ was not declared in this scope; did you mean ‘std::ifstream’?
  193 |     ifstream urandom("/dev/urandom",ios::in|ios::binary);
      |     ^~~~~~~~
      |     std::ifstream
/opt/openFrameworks/addons/ofxVisualProgramming/src/utils.h:194:8: error: ‘urandom’ was not declared in this scope; did you mean ‘srandom’?
  194 |     if(urandom){
      |        ^~~~~~~
      |        srandom
In file included from /opt/openFrameworks/addons/ofxVisualProgramming/src/PatchObject.h:37,
                 from /opt/openFrameworks/addons/ofxVisualProgramming/src/ofxVisualProgramming.h:48,
                 from src/includes.h:35,
                 from src/ofApp.h:44,
                 from src/main.cpp:35:
/opt/openFrameworks/addons/ofxVisualProgramming/src/utils.h:194:8: error: ‘urandom’ was not declared in this scope; did you mean ‘srandom’?
  194 |     if(urandom){
      |        ^~~~~~~
      |        srandom
/opt/openFrameworks/addons/ofxVisualProgramming/src/utils.h: In function ‘std::string execCmd(const char*)’:
/opt/openFrameworks/addons/ofxVisualProgramming/src/utils.h:267:22: error: ‘runtime_error’ was not declared in this scope; did you mean ‘std::runtime_error’?
  267 |     if (!pipe) throw runtime_error("popen() failed!");
      |                      ^~~~~~~~~~~~~
      |                      std::runtime_error
/opt/openFrameworks/addons/ofxVisualProgramming/src/utils.h: In function ‘std::string execCmd(const char*)’:
/opt/openFrameworks/addons/ofxVisualProgramming/src/utils.h:267:22: error: ‘runtime_error’ was not declared in this scope; did you mean ‘std::runtime_error’?
  267 |     if (!pipe) throw runtime_error("popen() failed!");
      |                      ^~~~~~~~~~~~~
      |                      std::runtime_error
/opt/openFrameworks/addons/ofxVisualProgramming/src/utils.h: In function ‘std::string execCmd(const char*)’:
/opt/openFrameworks/addons/ofxVisualProgramming/src/utils.h:267:22: error: ‘runtime_error’ was not declared in this scope; did you mean ‘std::runtime_error’?
  267 |     if (!pipe) throw runtime_error("popen() failed!");
      |                      ^~~~~~~~~~~~~
      |                      std::runtime_error
src/ofApp.cpp: In member function ‘void ofApp::drawImGuiInterface()’:
src/ofApp.cpp:1126:33: error: ‘filesystem’ has not been declared
 1126 |                                 filesystem::path tempPath(editedFilesPaths[actualCodeEditor].c_str());
      |                                 ^~~~~~~~~~
src/ofApp.cpp:1131:48: error: ‘tempPath’ was not declared in this scope
 1131 |                                 ofBufferToFile(tempPath,buff,false);
      |                                                ^~~~~~~~
src/ofApp.cpp: In member function ‘virtual void ofApp::keyPressed(ofKeyEventArgs&)’:
src/ofApp.cpp:1824:9: error: ‘filesystem’ has not been declared
 1824 |         filesystem::path tempPath(editedFilesPaths[actualCodeEditor].c_str());
      |         ^~~~~~~~~~
src/ofApp.cpp:1827:24: error: ‘tempPath’ was not declared in this scope
 1827 |         ofBufferToFile(tempPath,buff,false);
      |                        ^~~~~~~~
`
thanks for your help!

**Comment by d3cod3** [comment]
Right, i just fixed the issues with the openframeworks source, now the https://www.d3cod3.org/downloads/of_v0.12.0_linux64gcc6_release_Mosaic.tar.gz link is up and running again, please try again:

remove previous installation or failed installation of Mosaic
```
sudo rm -rf /opt/openframeworks
``` 

and

```
cd Mosaic-Installer
sudo ./mosaic_installer.sh
```

let me know how it went

**Comment by VrtXArt** [comment]
Thank you @d3cod3 .
In both OS are working fine.

Waiting for updates and hope Mosaic get stable soon.
