### ISSUE TITLE
compilation of 0.1.9 failing

### ISSUE THREAD

**Issue by baumgartnerniels** [d3cod3/Mosaic#9]
Hi there, 
I am trying to compile Mosaic on a Fedora 30 Linux. 
I don't know a lot about the c++ build toolchain, so I'm quite lost here. Hopefully someone here knows where to look for the root cuase of this error.
The build script exits with:
```
Compiling Mosaic for Release
make[1]: Entering directory '/opt/openFrameworks/apps/d3cod3/Mosaic'
make[1]: *** No rule to make target '/opt/openFrameworks/addons/obj/linux64/Release/ofxFaceTracker/./src/SplashScreen.o', needed by 'bin/Mosaic'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/opt/openFrameworks/apps/d3cod3/Mosaic'
make: *** [/opt/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2
++ last_command='make -j$NUMPU Release'
++ current_command='make -j$NUMPU Release'
+ echo '"make -j$NUMPU Release" command failed with exit code 2.'
"make -j$NUMPU Release" command failed with exit code 2.
```
Let me know if I should provide any logs or other info and where to find them.

**Comment by baumgartnerniels** [comment]
Never mind, i was missing the ofxFaceTracker addon in my addons folder.

**Comment by d3cod3** [comment]
OK!

Let me know how is working on Fedora, and if the build script need some tweaks (which one are you using?)
